name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Or windows-latest if you want to use Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install .NET SDK (if not already installed on the runner)
      run: |
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-6.0  # Adjust for your .NET version

    - name: Restore dependencies
      run: dotnet restore Demograx.sln

    - name: Build the project
      run: dotnet build Demograx.sln --configuration Release

    - name: Run tests
      run: dotnet test Demograx.sln --configuration Release --no-build --verbosity normal

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install .NET SDK (if not already installed on the runner)
      run: |
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-6.0  # Adjust for your .NET version

    - name: Publish project
      run: dotnet publish src/Demograx/Demograx.csproj -c Release -o ./publish

    - name: Upload published artifact
      uses: actions/upload-artifact@v2
      with:
        name: demograx-publish
        path: ./publish
