name: DemograX .NET Core Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner for Visual Studio projects

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up .NET SDK (ensure it's compatible with the project)
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  # Change to match the .NET version used in the project

    # Step 3: Restore dependencies (NuGet packages) using the correct path to the .csproj file
    - name: Restore dependencies
      run: dotnet restore src/DemograX/DemograX.csproj

    # Step 4: Build the project (use the correct path to the .csproj file)
    - name: Build the project
      run: dotnet build src/DemograX/DemograX.csproj --configuration Release

    # Step 5: Run unit tests (again, use the correct path to the .csproj file)
    - name: Run tests
      run: dotnet test src/DemograX/DemograX.csproj --configuration Release --no-restore

    # Step 6: Publish the project (optional step)
    - name: Publish the project
      run: |
        dotnet publish src/DemograX/DemograX.csproj --configuration Release --output ./publish
