name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Or windows-latest if you want to use Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'  # Specify the version of .NET you are using, e.g., 6.0, 7.0

    - name: Restore dependencies
      run: dotnet restore Demograx.sln

    - name: Build the project
      run: dotnet build Demograx.sln --configuration Release

    - name: Run tests
      run: dotnet test Demograx.sln --configuration Release --no-build --verbosity normal

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    - name: Publish project
      run: dotnet publish src/Demograx/Demograx.csproj -c Release -o ./publish

    - name: Upload published artifact
      uses: actions/upload-artifact@v2
      with:
        name: demograx-publish
        path: ./publish
